name: Bug Report
description: File a bug report.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  
  - type: textarea
    id: what-happened
    attributes:
      label: What happened? (Actual vs Expected Behavior)
      description: Please describe what happened and what you expected to happen.
      placeholder: Provide a clear description of the actual behavior and the expected outcome.
    validations:
      required: true

  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: Please provide detailed steps so we can reproduce the issue.
      placeholder: List the steps required to reproduce the bug.
    validations:
      required: true

  - type: input
    id: Skyrim-Version
    attributes:
      label: What Skyrim version are you using?
      description: Specify the Skyrim version number here.
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant log output (Expandable)
      description: Please paste any relevant log output here. This field is expandable for better readability and will be automatically formatted as shell code.
      render: shell
      placeholder: Paste your logs here.   
