name: Feature Request
description: Suggest a feature for this mod
title: "[FEATURE]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: "## Feature Request"
  - type: input
    id: title
    attributes:
      label: "Feature Title"
      description: "A clear and concise title for the feature."
      placeholder: "Enter the title for the feature request"
  - type: textarea
    id: motivation
    attributes:
      label: "Motivation"
      description: "Please outline the motivation for the request."
      placeholder: "Why is this feature important to you?"
  - type: textarea
    id: description
    attributes:
      label: "Feature Description"
      description: "A detailed description of the feature."
      placeholder: "Describe the feature you'd like to see."
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional Context"
      description: "Add any other context or screenshots about the feature request here."
      placeholder: "Add context or links to related issues, screenshots, etc."
